version: "3"
services:
  webui:
    # replace username/repo:tag with your name and image details
    image: gofcc
    ports:
      - "4200:4200"
    networks:
      - webnet
  testserver:
    image: testserver
    ports:
      - "4000:4000"
    networks:
      - webnet
networks:
  webnet: